name: Test and document
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ls ${{ github.workspace }}
      - run: pip install -r ${{ github.workspace }}/requirements.txt
      - run: python3 -m unittest
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: pip install pdoc3
      - run: cd  ${{ github.workspace }} && pdoc --html dpyr --force
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email '
          git add .
          git commit -m "Update documentation (auto)"
          git push