name: Test and document
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ls ${{ github.workspace }}
      - run: pip install -r ${{ github.workspace }}/requirements.txt
      - run: python3 -m unittest
  Create-Documentation:
    runs-on: ubuntu-latest
    needs: Run-Tests
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: pip install -r ${{ github.workspace }}/requirements.txt
      - run: pip install pdoc3
      - run: cd  ${{ github.workspace }} && pdoc --html dpyr --force
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'codyburker@gmail.com'
          git add .
          git commit -m "Update documentation (auto)"
      name: Push
      run: git push